artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Stanlito-AI/Branching/blob/master/Chicken-fecal-images.zip
  locals_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion